/**
 * Port of parse_rfi.py's xlsx_to_rfi_dict.
 *
 * Reads an RFI .xlsx (the template generated by build_rfi_template.py)
 * and flattens it into the dict shape declared by rfi_schema.json.
 */
import ExcelJS from "exceljs";

const SHEET_CLIENTE = "Cliente";
const SHEET_PROYECTO = "Proyecto";
const SHEET_RECURSOS = "Recursos";
const SHEET_RESIDUOS = "Residuos";
const SHEET_MANO_OBRA = "Mano_Obra";
const SHEET_CRONOGRAMA = "Cronograma";
const SHEET_COMPONENTES_FILE = "Componentes_File";

const CATEGORY_SHEET_MAP: Record<string, string> = {
  A_exploracion_directa: "A_Exploracion",
  B_infraestructura_lineal: "B_Lineal",
  C_auxiliares: "C_Auxiliares",
  D_gestion_aguas: "D_Aguas",
  E_residuos_y_materiales: "E_Residuos",
  F_energia_y_combustibles: "F_Energia",
};
const SHEET_G = "G_Otros";

type Cell = string | number | boolean | Date | null | undefined;

function coerce(value: unknown): Cell {
  if (value === null || value === undefined) return null;
  if (typeof value === "string") {
    const t = value.trim();
    return t === "" ? null : t;
  }
  if (typeof value === "object" && "result" in (value as object)) {
    return coerce((value as { result: unknown }).result);
  }
  if (typeof value === "object" && "text" in (value as object)) {
    return coerce((value as { text: unknown }).text);
  }
  if (typeof value === "object" && "richText" in (value as object)) {
    const rt = (value as { richText: { text: string }[] }).richText;
    return rt.map((r) => r.text).join("");
  }
  if (
    typeof value === "string" ||
    typeof value === "number" ||
    typeof value === "boolean" ||
    value instanceof Date
  ) {
    return value as Cell;
  }
  return null;
}

function readKvSheet(
  workbook: ExcelJS.Workbook,
  sheetName: string,
): Record<string, Cell> {
  const ws = workbook.getWorksheet(sheetName);
  if (!ws) return {};

  const header: string[] = [];
  ws.getRow(1).eachCell((cell, col) => {
    const v = coerce(cell.value);
    header[col - 1] = typeof v === "string" ? v : "";
  });
  const iCampo = header.indexOf("Campo");
  const iValor = header.indexOf("Valor");
  if (iCampo < 0 || iValor < 0) return {};

  const out: Record<string, Cell> = {};
  for (let r = 2; r <= ws.rowCount; r++) {
    const row = ws.getRow(r);
    const key = coerce(row.getCell(iCampo + 1).value);
    if (typeof key !== "string" || !key) continue;
    const value = coerce(row.getCell(iValor + 1).value);
    if (value !== null && value !== undefined) {
      out[key] = value;
    }
  }
  return out;
}

function readTableSheet(
  workbook: ExcelJS.Workbook,
  sheetName: string,
): Array<Record<string, Cell>> {
  const ws = workbook.getWorksheet(sheetName);
  if (!ws) return [];

  const header: string[] = [];
  ws.getRow(1).eachCell((cell, col) => {
    const v = coerce(cell.value);
    header[col - 1] = typeof v === "string" ? v : "";
  });

  const rows: Array<Record<string, Cell>> = [];
  for (let r = 2; r <= ws.rowCount; r++) {
    const row = ws.getRow(r);
    const record: Record<string, Cell> = {};
    let hasAny = false;
    for (let c = 0; c < header.length; c++) {
      const key = header[c];
      if (!key) continue;
      const v = coerce(row.getCell(c + 1).value);
      if (v !== null && v !== undefined) {
        record[key] = v;
        hasAny = true;
      }
    }
    if (hasAny) rows.push(record);
  }
  return rows;
}

function splitCsvField(raw: Cell): string[] {
  if (raw === null || raw === undefined) return [];
  const s = String(raw).replace(/;/g, ",");
  return s
    .split(",")
    .map((p) => p.trim())
    .filter(Boolean);
}

function readComponenteRow(
  row: Record<string, Cell>,
): { _componente: string; [k: string]: Cell } | null {
  const nombre = row["Componente"];
  if (typeof nombre !== "string" || !nombre.trim()) return null;
  const record: { _componente: string; [k: string]: Cell } = {
    _componente: nombre.trim(),
  };
  for (const [key, value] of Object.entries(row)) {
    if (key === "Componente" || key === "Aplica" || key === "Aplica?") continue;
    if (value === null || value === undefined) continue;
    const attr = key.toLowerCase().trim().replace(/ /g, "_").replace(/\?/g, "");
    record[attr] = value;
  }
  return record;
}

export interface RfiDict {
  cliente: Record<string, unknown>;
  proyecto: Record<string, unknown>;
  componentes_proyecto: Record<string, unknown>;
  requerimientos_recursos?: Record<string, unknown>;
  residuos?: Record<string, unknown>;
  mano_obra?: Record<string, unknown>;
  cronograma?: Record<string, unknown>;
  componentes_file?: string;
}

export async function parseRfiXlsx(buffer: ArrayBuffer): Promise<RfiDict> {
  const wb = new ExcelJS.Workbook();
  await wb.xlsx.load(buffer);

  const cliente = readKvSheet(wb, SHEET_CLIENTE);
  const proyectoRaw = readKvSheet(wb, SHEET_PROYECTO);

  const proyecto: Record<string, unknown> = { ...proyectoRaw };
  if ("commodity" in proyecto) {
    proyecto.commodity = splitCsvField(proyecto.commodity as Cell);
  }
  if ("metodo_exploracion" in proyecto) {
    proyecto.metodo_exploracion = splitCsvField(
      proyecto.metodo_exploracion as Cell,
    );
  }
  if ("zona_utm" in proyecto) {
    const n = Number(proyecto.zona_utm);
    if (Number.isFinite(n)) proyecto.zona_utm = Math.trunc(n);
  }
  if ("area_total_ha" in proyecto) {
    const n = Number(proyecto.area_total_ha);
    if (Number.isFinite(n)) proyecto.area_total_ha = n;
  }
  if ("proyecto_brownfield" in proyecto) {
    const v = proyecto.proyecto_brownfield;
    if (typeof v === "string") {
      proyecto.proyecto_brownfield = ["true", "si", "sí", "yes", "1"].includes(
        v.toLowerCase().trim(),
      );
    }
  }

  const componentesProyecto: Record<string, unknown> = {};
  for (const [categoryKey, sheetName] of Object.entries(CATEGORY_SHEET_MAP)) {
    const block: Record<string, Record<string, unknown>> = {};
    for (const row of readTableSheet(wb, sheetName)) {
      const comp = readComponenteRow(row);
      if (!comp) continue;
      const slug = comp._componente;
      const attrs: Record<string, unknown> = {};
      for (const [k, v] of Object.entries(comp)) {
        if (k === "_componente") continue;
        if (k === "cantidad") {
          const n = Number(v);
          if (Number.isFinite(n)) attrs.cantidad = Math.trunc(n);
        } else if (typeof v === "number" || typeof v === "string" || typeof v === "boolean") {
          // Try numeric coercion for known numeric attrs; leave strings otherwise
          if (typeof v === "string" && /^-?\d+(\.\d+)?$/.test(v.trim())) {
            attrs[k] = Number(v);
          } else {
            attrs[k] = v;
          }
        }
      }
      block[slug] = attrs;
    }
    if (Object.keys(block).length > 0) {
      componentesProyecto[categoryKey] = block;
    }
  }

  // G_otros (free-form)
  const otros: Array<Record<string, unknown>> = [];
  for (const row of readTableSheet(wb, SHEET_G)) {
    const nombre = row["Nombre"] ?? row["Componente"];
    const cantidad = row["Cantidad"];
    if (
      typeof nombre !== "string" ||
      !nombre.trim() ||
      cantidad === undefined ||
      cantidad === null ||
      Number(cantidad) === 0
    ) {
      continue;
    }
    otros.push({
      nombre: String(nombre).trim(),
      cantidad: Math.trunc(Number(cantidad)),
      descripcion: String(row["Descripcion"] ?? row["Descripción"] ?? "").trim(),
    });
  }
  if (otros.length > 0) componentesProyecto.G_otros = otros;

  const rfi: RfiDict = {
    cliente,
    proyecto,
    componentes_proyecto: componentesProyecto,
  };

  const recursos = readKvSheet(wb, SHEET_RECURSOS);
  if (Object.keys(recursos).length > 0) rfi.requerimientos_recursos = recursos;
  const residuos = readKvSheet(wb, SHEET_RESIDUOS);
  if (Object.keys(residuos).length > 0) rfi.residuos = residuos;
  const manoObra = readKvSheet(wb, SHEET_MANO_OBRA);
  if (Object.keys(manoObra).length > 0) rfi.mano_obra = manoObra;

  const cronograma = readKvSheet(wb, SHEET_CRONOGRAMA);
  if (Object.keys(cronograma).length > 0) {
    if ("duracion_meses" in cronograma) {
      const n = Number(cronograma.duracion_meses);
      if (Number.isFinite(n)) cronograma.duracion_meses = Math.trunc(n);
    }
    rfi.cronograma = cronograma as Record<string, unknown>;
  }

  const cf = readKvSheet(wb, SHEET_COMPONENTES_FILE);
  if (typeof cf.componentes_file === "string") {
    rfi.componentes_file = cf.componentes_file;
  }

  // Convert Cell-typed values in cliente/proyecto/blocks to plain JS values for JSON.
  return JSON.parse(JSON.stringify(rfi)) as RfiDict;
}
